title: Brenton's Blog
author: Brenton Forrest
email: your-email@domain.com
description: > My awesomeblog about everything 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
